create table if not exists landing_visits (
  id bigint generated by default as identity primary key,
  session_id text,
  fingerprint text,
  ref text default 'direct',
  utm_medium text,
  utm_campaign text,
  utm_content text,
  landing_page text,
  referrer text,
  user_agent text,
  screen_width integer,
  screen_height integer,
  timezone text,
  created_at timestamptz not null default now()
);

create table if not exists telegram_clicks (
  id bigint generated by default as identity primary key,
  session_id text,
  fingerprint text,
  ref text default 'direct',
  utm_medium text,
  utm_campaign text,
  utm_content text,
  landing_page text,
  referrer text,
  user_agent text,
  dwell_seconds numeric default 0,
  classification text default 'likely_real',
  reasons jsonb default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table landing_visits enable row level security;
alter table telegram_clicks enable row level security;

create index if not exists landing_visits_created_at_idx
on landing_visits(created_at);

create index if not exists telegram_clicks_created_at_idx
on telegram_clicks(created_at);

create index if not exists landing_visits_fingerprint_idx
on landing_visits(fingerprint);

create index if not exists telegram_clicks_fingerprint_idx
on telegram_clicks(fingerprint);
